/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

const classleadsData = require("./docs/classleads/classleads_data.json");

const classSkillsDocId = "classleads/class-skills-tree";
const classSkillsDocPath = `/nex-files/docs/${classSkillsDocId}`;
const classleadsSidebarItems = Object.entries(classleadsData.classes || {})
  .sort(([classA], [classB]) => classA.localeCompare(classB))
  .map(([className, skills]) => ({
    type: "category",
    label: className,
    collapsed: true,
    items: (Array.isArray(skills) ? skills : []).map((skill) => ({
      type: "link",
      label: skill,
      href: `${classSkillsDocPath}#${skill.toLowerCase()}`,
    })),
  }));

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  defaultSidebar: [{ type: "autogenerated", dirName: "." }],
  eventStreamSidebar: [
    {
      type: "category",
      label: "eventStream",
      link: { type: "doc", id: "eventStream/introduction" },
      items: [
        "eventStream/introduction",
        "eventStream/api",
        "eventStream/examples",
        {
          type: "category",
          label: "nexAction",
          link: { type: "doc", id: "eventStream/nexAction/introduction" },
          items: ["eventStream/nexAction/introduction"],
        },
        {
          type: "category",
          label: "nexSkills",
          link: { type: "doc", id: "eventStream/nexSkills/introduction" },
          items: [
            "eventStream/nexSkills/introduction",
            "eventStream/nexSkills/examples",
            "eventStream/nexSkills/structure",
          ],
          /*items: [
            {
              type: "autogenerated",
              dirName: "eventStream/nexSkills",
            },
          ],*/
        },
      ],
    },
  ],
  nexSysSidebar: [
    {
      type: "category",
      label: "nexSys",
      /*
      link: {
        type: "generated-index",
        title: "Core Features",
        description: "Introduction to nexSys Features",
        keywords: ["nexSys"],
      },
      */
      link: { type: "doc", id: "nexSys/introduction" },
      items: [
        "nexSys/introduction",
        "nexSys/installation",
        "nexSys/configuration",
        "nexSys/queues",
        "nexSys/prompt",
        "nexSys/prioSwaps",
        "nexSys/api",
        "nexSys/events",

        {
          type: "category",
          label: "Affs",
          link: {
            type: "generated-index",
            title: "Core Features",
            description: "Introduction to nexSys Features",
            keywords: ["nexSys"],
          },
          items: ["nexSys/affs/functions"],
        },
        {
          type: "category",
          label: "Defs",
          link: {
            type: "generated-index",
            title: "Core Features",
            description: "Introduction to nexSys Features",
            keywords: ["nexSys"],
          },
          items: ["nexSys/affs/functions"],
        },
        {
          type: "category",
          label: "Bals",
          link: {
            type: "generated-index",
            title: "Core Features",
            description: "Introduction to nexSys Features",
            keywords: ["nexSys"],
          },
          items: ["nexSys/affs/functions"],
        },
      ],
    },
  ],
  nexMapSidebar: [
    {
      type: "category",
      label: "nexMap",
      link: { type: "doc", id: "nexMap/introduction" },
      items: [
        "nexMap/introduction",
        "nexMap/installation",
        "nexMap/configuration",
        "nexMap/npcDatabase",
        "nexMap/api",
      ],
    },
  ],
  nexGuiSidebar: [
    {
      type: "category",
      label: "nexGui",
      link: { type: "doc", id: "nexGui/introduction" },
      items: ["nexGui/introduction"],
    },
  ],

  insightSidebar: [
    {
      type: "category",
      label: "insight",
      link: { type: "doc", id: "insight/introduction" },
      items: ["insight/introduction", "insight/api"],
    },
  ],
  classleadsSidebar: [
    { type: "doc", id: classSkillsDocId },
    ...classleadsSidebarItems,
  ],
  nexusSidebar: [
    {
      type: "category",
      label: "Nexus",
      link: {
        type: "generated-index",
        title: "Nexus Web Client",
        description:
          "Introduction to Nexus Web Client Features, Functionality, and JavaScript",
        keywords: ["nexus"],
      },
      items: [
        {
          type: "doc",
          label: "API",
          id: "nexus/API",
        },
        {
          type: "doc",
          label: "Tutorials",
          id: "nexus/tutorials",
        },
        {
          type: "doc",
          label: "Quick Reference",
          id: "nexus/quickReference",
        },
        {
          type: "doc",
          label: "Useful Snippets",
          id: "nexus/snippets",
        },
      ],
    },
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;

