/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

const classleadsData = require("./docs/classleads/classleads_data.json");

const classSkillsDocId = "classleads/class-skills-tree";
const classSkillsDocPath = `/nex-files/docs/${classSkillsDocId}`;
const classleadsSidebarItems = Object.entries(classleadsData.classes || {})
  .sort(([classA], [classB]) => classA.localeCompare(classB))
  .map(([className, skills]) => ({
    type: "category",
    label: className,
    collapsed: true,
    items: (Array.isArray(skills) ? skills : []).map((skill) => ({
      type: "link",
      label: skill,
      href: `${classSkillsDocPath}#${skill.toLowerCase()}`,
    })),
  }));

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  defaultSidebar: [{ type: "autogenerated", dirName: "." }],
  eventStreamSidebar: [
    {
      type: "category",
      label: "eventStream",
      link: { type: "doc", id: "eventStream/introduction" },
      items: [
        "eventStream/introduction",
        "eventStream/api",
        "eventStream/examples",
        {
          type: "category",
          label: "nexAction",
          link: { type: "doc", id: "eventStream/nexAction/introduction" },
          items: ["eventStream/nexAction/introduction"],
        },
        {
          type: "category",
          label: "nexSkills",
          link: { type: "doc", id: "eventStream/nexSkills/introduction" },
          items: [
            "eventStream/nexSkills/introduction",
            "eventStream/nexSkills/examples",
            "eventStream/nexSkills/structure",
          ],
          /*items: [
            {
              type: "autogenerated",
              dirName: "eventStream/nexSkills",
            },
          ],*/
        },
      ],
    },
  ],
  nexSysSidebar: [
    {
      type: "category",
      label: "nexSys",
      /*
      link: {
        type: "generated-index",
        title: "Core Features",
        description: "Introduction to nexSys Features",
        keywords: ["nexSys"],
      },
      */
      link: { type: "doc", id: "nexSys/introduction" },
      items: [
        "nexSys/introduction",
        "nexSys/installation",
        "nexSys/quickstart",
        "nexSys/configuration",
        "nexSys/curing",
        "nexSys/queues",
        "nexSys/prompt",
        "nexSys/prioSwaps",
        "nexSys/commands",
        "nexSys/api",
        "nexSys/events",
        "nexSys/troubleshooting",
        {
          type: "category",
          label: "Reference",
          link: {
            type: "generated-index",
            title: "nexSys Reference",
            description: "Generated tables for afflictions, defences, cures, and caches.",
            keywords: ["nexSys", "reference"],
          },
          items: [
            "nexSys/reference/afflictions",
            "nexSys/reference/defences",
            "nexSys/reference/balances",
            "nexSys/reference/cures",
            "nexSys/reference/cache",
          ],
        },
      ],
    },
  ],
  nexMapSidebar: [
    {
      type: "category",
      label: "nexMap",
      link: { type: "doc", id: "nexMap/introduction" },
      items: [
        "nexMap/introduction",
        "nexMap/installation",
        "nexMap/quickstart",
        "nexMap/configuration",
        "nexMap/pathing",
        "nexMap/travel",
        "nexMap/npcDatabase",
        "nexMap/commands",
        "nexMap/api",
        "nexMap/events",
        "nexMap/troubleshooting",
        {
          type: "category",
          label: "Reference",
          link: {
            type: "generated-index",
            title: "nexMap Reference",
            description: "Generated tables for travel options and mapping data.",
            keywords: ["nexMap", "reference"],
          },
          items: [
            "nexMap/reference/travel",
            "nexMap/reference/directions",
            "nexMap/reference/environments",
            "nexMap/reference/areas",
          ],
        },
      ],
    },
  ],
  nexGuiSidebar: [
    {
      type: "category",
      label: "nexGui",
      link: { type: "doc", id: "nexGui/introduction" },
      items: [
        "nexGui/introduction",
        "nexGui/installation",
        "nexGui/quickstart",
        "nexGui/configuration",
        "nexGui/commands",
        "nexGui/api",
        "nexGui/events",
        "nexGui/troubleshooting",
        {
          type: "category",
          label: "Tabs",
          link: {
            type: "generated-index",
            title: "nexGui Tabs",
            description:
              "Reference pages for every UI tab and panel provided by nexGui.",
            keywords: ["nexGui", "tabs"],
          },
          items: [
            "nexGui/tabs/room-inventory",
            "nexGui/tabs/room-npcs",
            "nexGui/tabs/room-players",
            "nexGui/tabs/game-options",
            "nexGui/tabs/game-feed",
            "nexGui/tabs/party",
            "nexGui/tabs/missing-defences",
            "nexGui/tabs/timers",
            "nexGui/tabs/system-stream",
            "nexGui/tabs/combat-stream",
            "nexGui/tabs/play-stats",
            "nexGui/tabs/target-state",
            "nexGui/tabs/self-state",
            "nexGui/tabs/infinite-display",
            "nexGui/tabs/infinite-buffer",
          ],
        },
      ],
    },
  ],

  insightSidebar: [
    {
      type: "category",
      label: "insight",
      link: { type: "doc", id: "insight/introduction" },
      items: [
        "insight/introduction",
        "insight/installation",
        "insight/quickstart",
        "insight/configuration",
        "insight/api",
        "insight/events",
        "insight/troubleshooting",
        {
          type: "category",
          label: "Reference",
          link: {
            type: "generated-index",
            title: "insight Reference",
            description: "Generated tables for afflictions, cures, defences, and balances.",
            keywords: ["insight", "reference"],
          },
          items: [
            "insight/reference/afflictions",
            "insight/reference/cures",
            "insight/reference/defences",
            "insight/reference/balances",
          ],
        },
      ],
    },
  ],
  classleadsSidebar: [
    { type: "doc", id: classSkillsDocId },
    ...classleadsSidebarItems,
  ],
  nexusSidebar: [
    {
      type: "category",
      label: "Nexus",
      link: {
        type: "generated-index",
        title: "Nexus Web Client",
        description:
          "Introduction to Nexus Web Client Features, Functionality, and JavaScript",
        keywords: ["nexus"],
      },
      items: [
        {
          type: "doc",
          label: "API",
          id: "nexus/API",
        },
        {
          type: "doc",
          label: "Tutorials",
          id: "nexus/tutorials",
        },
        {
          type: "doc",
          label: "Quick Reference",
          id: "nexus/quickReference",
        },
        {
          type: "doc",
          label: "Useful Snippets",
          id: "nexus/snippets",
        },
      ],
    },
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
